Update predict_custom_trained_model_sample.py
This snippet of code were giving me this error:

google.api_core.exceptions.FailedPrecondition: 400 "Prediction failed: Exception during sklearn prediction: predict() got an unexpected keyword argument 'parameters'"

Deleting the step of parameters, I was able to use the endpoint as I'm predicting a local model, for example. I'm also suggesting return the predictions instead of a print to let the user decide what to do with the response.

With these changes I'm able to perform this following code:

pred = predict_custom_trained_model_sample(
    project=project,
    endpoint_id=endrpoind_id,
    location=location,
    instances=[[5.1, 3.5, 1.4, 0.2], [5.1, 3.5, 1.4, 0.2]]
)