feat: Add Grounding feature to PredictionService.GenerateContent feat: Add Retrieval feat: Add GoogleSearchRetrieval feat: Add VertexAiSearch feat: Add Tool.retrieval feat: Add Tool.google_search_retrieval feat: Add Candidate.grounding_metadata
docs: A comment for message `Tool` is changed
docs: A comment for field `tools` in message `.google.cloud.aiplatform.v1beta1.GenerateContentRequest` is changed
docs: A comment for field `tools` in message `.google.cloud.aiplatform.v1beta1.GenerateContentRequest` is changed
PiperOrigin-RevId: 605743031

Source-Link: https://github.com/googleapis/googleapis/commit/e183baf16610b925fc99e628fc539e118bc3348a

Source-Link: https://github.com/googleapis/googleapis-gen/commit/1f35985a865bce189bc3de39e0200681025ee213
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiMWYzNTk4NWE4NjViY2UxODliYzNkZTM5ZTAyMDA2ODEwMjVlZTIxMyJ9

fix!: remove field `max_wait_duration` from message Scheduling
fix!: remove method `CountTokens` from service LlmUtilityService
feat: add psc_automated_endpoints to IndexPrivateEndpoints
feat: add update_mask to UpsertDatapointsRequest
feat: add more RecordErrorType enum values
feat: add request_response_logging_schema_version to ModelDeploymentMonitoringBigQueryTable
feat: add resource_title, resource_use_case, resource_description to RegionalResourceReferences
docs: deprecate use_case and description in ResourceReference
feat: add deploy_gke, open_tine_tuning_pipelines, open_notebooks to CallToAction
docs: minor changes to comments

PiperOrigin-RevId: 605668103

Source-Link: https://github.com/googleapis/googleapis/commit/f5833986f07c975c67bf6f635a5bb930b3354f85

Source-Link: https://github.com/googleapis/googleapis-gen/commit/74cf4058417bd2a6411395d286c34fb27088a76d
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiNzRjZjQwNTg0MTdiZDJhNjQxMTM5NWQyODZjMzRmYjI3MDg4YTc2ZCJ9

fix!: remove field `max_wait_duration` from message Scheduling
feat: add psc_automated_endpoints to IndexPrivateEndpoints
feat: add request_response_logging_schema_version to ModelDeploymentMonitoringBigQueryTable
feat: add resource_title, resource_use_case, resource_description to RegionalResourceReferences
feat: add deploy_gke, open_tine_tuning_pipelines, open_notebooks to CallToAction
docs: deprecate use_case and description in ResourceReference
docs: minor changes to comments

PiperOrigin-RevId: 605667976

Source-Link: https://github.com/googleapis/googleapis/commit/3b25a48cfd09b9fc8a9d4a539a0328594e0c2668

Source-Link: https://github.com/googleapis/googleapis-gen/commit/b8402de22611a3b7bffa59b075891e5b29a0d554
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiYjg0MDJkZTIyNjExYTNiN2JmZmE1OWIwNzU4OTFlNWIyOWEwZDU1NCJ9

feat: add SearchNearestEntities rpc to FeatureOnlineStoreService in aiplatform v1

PiperOrigin-RevId: 604763557

Source-Link: https://github.com/googleapis/googleapis/commit/5acba7c6c7c8961fe6ff05388b4636b686bef9d1

Source-Link: https://github.com/googleapis/googleapis-gen/commit/0f0c9b140781bc3831a30eae944f0831e522dea3
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiMGYwYzliMTQwNzgxYmMzODMxYTMwZWFlOTQ0ZjA4MzFlNTIyZGVhMyJ9

fix: fix `ValueError` in `test__validate_universe_domain`

PiperOrigin-RevId: 604699565

Source-Link: https://github.com/googleapis/googleapis/commit/cd3eabf5968bbc91685e2eae8efb099e4d55bb5c

Source-Link: https://github.com/googleapis/googleapis-gen/commit/01f69ba7a13d59e6f45e243359b91a6e896221f8
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiMDFmNjliYTdhMTNkNTllNmY0NWUyNDMzNTliOTFhNmU4OTYyMjFmOCJ9

chore: set packed = false on field_behavior extension

PiperOrigin-RevId: 604675854

Source-Link: https://github.com/googleapis/googleapis/commit/42c04fea4338ba626095ec2cde5ea75827191581

Source-Link: https://github.com/googleapis/googleapis-gen/commit/a1ed8a97a00d02fe456f6ebd4160c5b2b000ad75
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiYTFlZDhhOTdhMDBkMDJmZTQ1NmY2ZWJkNDE2MGM1YjJiMDAwYWQ3NSJ9

fix: Resolve AttributeError 'Credentials' object has no attribute 'universe_domain'

fix: Add google-auth as a direct dependency

fix: Add staticmethod decorator to methods added in v1.14.0

chore: Update gapic-generator-python to v1.14.1
PiperOrigin-RevId: 603728206

Source-Link: https://github.com/googleapis/googleapis/commit/9063da8b4d45339db4e2d7d92a27c6708620e694

Source-Link: https://github.com/googleapis/googleapis-gen/commit/891c67d0a855b08085eb301dabb14064ef4b2c6d
Copy-Tag: eyJwIjoiLmdpdGh1Yi8uT3dsQm90LnlhbWwiLCJoIjoiODkxYzY3ZDBhODU1YjA4MDg1ZWIzMDFkYWJiMTQwNjRlZjRiMmM2ZCJ9