Update setup.py
Change `packaging` to support `packaging-23.0`

To avoid error 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-aiplatform 1.23.0 requires packaging<22.0.0dev,>=14.3, but you have packaging 23.0 which is incompatible.
```

Other Google Cloud Client Libraries support or require a newer version